paths:
  data: "../../laba2/lab2/data/processed/reviews_processed.parquet"
  model_dir: "models/"
  vocab_path: "models/vocab.json"

training:
  batch_size: 64
  num_epochs: 8
  lr: 0.0008
  max_len: 120

model:
  embedding_dim: 128
  hidden_dim: 128
  num_layers: 2
  dropout: 0.3
  bidirectional: true

labels:
  - negative
  - neutral
  - positive